name: Deploy workflow
on: 
    push:
      branches:
        - main

env: 
    AZURE_WEBAPP_NAME: mission-4-deployments
    AZURE_WEBAPP_PACKAGE_PATH: '.'
    NODE_VERSION: v16.17.0
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: ${{env.NODE_VERSION}}
      
      - name: npm install
        run: 
          # install the project
          npm install
          npm install nodemon
        working-directory: ${{env. AZURE_WEBAPP_PACKAGE_PATH}}

      - name: npm build
        run: 
          # Build the project
          npm run build --if-present
        working-directory: ${{env. AZURE_WEBAPP_PACKAGE_PATH}}

      - name: npm test
        run: 
          # test the project
          npm run test --if-present
        working-directory: ${{env. AZURE_WEBAPP_PACKAGE_PATH}}
      
      - name: 'Azure Login'
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run Azure'            
        run: |
          az webapp list --query "[?state=='Running']"

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}
          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}